# Generated by Django 5.1.4 on 2024-12-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.DecimalField(decimal_places=0, max_digits=4)),
                ('message', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'message',
            },
        ),
    ]
